### ISSUE TITLE
gettin ssl error

### ISSUE THREAD

**Issue by danmmelo** [ibm-messaging/event-streams-samples#25] opened 2018-05-29 16:43 UTC
{ severity: 7,
  fac: 'TERM',
  message: '[thrd:sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix]: sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:main]: Purging reply queue' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix]: sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:main]: Decommissioning internal broker' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd:sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix]: sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Bad address)' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:main]: Join 5 broker thread(s)' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Operation now in progress)' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd::0/internal]: :0/internal: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Operation now in progress)' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Operation now in progress)' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix]: sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix]: sasl_ssl://"kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'STATE',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Broker changed state CONNECT -> DOWN' }
{ severity: 7,
  fac: 'STATE',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Broker changed state CONNECT -> DOWN' }
{ severity: 7,
  fac: 'BROADCAST',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: Broadcasting state change' }
{ severity: 7,
  fac: 'STATE',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Broker changed state CONNECT -> DOWN' }
{ severity: 7,
  fac: 'BROADCAST',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: Broadcasting state change' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BROADCAST',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: Broadcasting state change' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd::0/internal]: :0/internal: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Operation timed out)' }
{ severity: 7,
  fac: 'STATE',
  message: '[thrd::0/internal]: :0/internal: Broker changed state UP -> DOWN' }
{ severity: 7,
  fac: 'BROADCAST',
  message: '[thrd::0/internal]: Broadcasting state change' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd::0/internal]: :0/internal: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd::0/internal]: :0/internal: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:main]: Main background thread exiting' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:app]: Destroying op queues' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:app]: Destroying SSL CTX' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:app]: Termination done: freeing resources' }

**Comment by schulz2** [comment] 2018-05-30 07:30
Hi Daniele,

on an internal channel I saw that there was an Bluemix outage yesterday in US South which affected MessageHub. Can your problem be caused by this, too? For instance, have you worked with that sample before and it stopped working yesterday?

Kind regards
Norbert

**Comment by danmmelo** [comment] 2018-05-30 22:04
Hi!


I am having the same issue today...and i did change anything...have you tried and it is working for you?Because i just create an instance of the message hub and and i've tried to connect using the code in github...


fac: 'TERMINATE',
  message: '[thrd:main]: Join 6 broker thread(s)' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd::0/internal]: :0/internal: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'DESTROY',
  message: '[thrd:main]: Destroy internal' }
{ severity: 7,
  fac: 'DESTROY',
  message: '[thrd:main]: Removing all topics' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:main]: Purging reply queue' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:main]: Decommissioning internal broker' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd:sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:main]: Join 6 broker thread(s)' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd:sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Undefined error: 0)' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka01-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd:sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd:sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Undefined error: 0)' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Undefined error: 0)' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka03-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka02-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'TERM',
  message: '[thrd::0/internal]: :0/internal: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Undefined error: 0)' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Undefined error: 0)' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd:sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka04-prod02.messagehub.services.us-south.bluemix.net:9093/bootstrap: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd::0/internal]: :0/internal: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Operation timed out)' }
{ severity: 7,
  fac: 'STATE',
  message: '[thrd::0/internal]: :0/internal: Broker changed state UP -> DOWN' }
{ severity: 7,
  fac: 'BROADCAST',
  message: '[thrd::0/internal]: Broadcasting state change' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd::0/internal]: :0/internal: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd::0/internal]: :0/internal: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd::0/internal]: :0/internal: Handle is terminating: failed 0 request(s) in retry+outbuf' }
{ severity: 7,
  fac: 'BROKERFAIL',
  message: '[thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Operation timed out)' }
{ severity: 7,
  fac: 'STATE',
  message: '[thrd::0/internal]: :0/internal: Broker changed state UP -> DOWN' }
{ severity: 7,
  fac: 'BROADCAST',
  message: '[thrd::0/internal]: Broadcasting state change' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd::0/internal]: :0/internal: Purging bufq with 0 buffers' }
{ severity: 7,
  fac: 'BUFQ',
  message: '[thrd::0/internal]: :0/internal: Updating 0 buffers on connection reset' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:main]: Main background thread exiting' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:app]: Destroying op queues' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:app]: Destroying SSL CTX' }
{ severity: 7,
  fac: 'TERMINATE',
  message: '[thrd:app]: Termination done: freeing resources' }





________________________________
De: Norbert Schulz <notifications@github.com>
Enviado: quarta-feira, 30 de maio de 2018 04:30
Para: ibm-messaging/message-hub-samples
Cc: Daniele Melo; Author
Assunto: Re: [ibm-messaging/message-hub-samples] gettin ssl error (#25)


Hi Daniele,

on an internal channel I saw that there was an Bluemix outage yesterday in US South which affected MessageHub. Can your problem be caused by this, too? For instance, have you worked with that sample before and it stopped working yesterday?

Kind regards
Norbert

**Comment by danmmelo** [comment] 2018-06-05 13:48
Having the same issue...could someone help?

**Comment by mimaison** [comment] 2018-06-05 14:04
Hi @danmmelo , unfortunately the logs you pasted are not really useful. We test these samples daily and know they work fine. It's probably a configuration issue, and your system might be missing a few required libraries when it compiled node-rdkafka/librdkafka. 

Can you tell us your OS, oncluding version? and paste the output of `npm install` (after having cleared `./node-modules` ?

**Comment by mimaison** [comment] 2018-09-28 11:10
No reply since the 5th of June, closing

**Closed by mimaison** 2018-09-28 11:10 UTC
